Exclude ubuntu-22.04 / ruby 2.2 from CI
This avoids the following error:
     Bundler 2 requires Ruby 2.3+, using Bundler 1 on Ruby <= 2.2
     /opt/hostedtoolcache/Ruby/2.2.10/x64/bin/gem install bundler -v ~> 1.0
     ERROR:  While executing gem ... (RuntimeError)
         Marshal.load reentered at marshal_load

See https://github.com/ruby/setup-ruby/issues/496

This works fine on ubuntu 20.04 and 24.04.